version: '2'
services:
    web:
        build: ./docker/web
        ports:
            - 8080:80
        depends_on:
            - db
            - rethink_db
        volumes:
            - .:/var/www
    db:
        image: postgres
        volumes:
            - ./app/data/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: roapp
            POSTGRES_USER: roapp
            POSTGRES_DB: roapp
    rethink_db:
        image: rethinkdb
        volumes:
            - ./app/data/rethinkdb:/data

