imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: mapping_value_based.yml }
    - { resource: mapping_time_based.yml }
    - { resource: secrets.yml }
    - { resource: gateway.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fa

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    translator: { fallbacks: ['%locale%'] }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'form/form_semantic_layout.html.twig'
        - 'RoappMediaBundle:form:fields.html.twig'
        - 'VichUploaderBundle:Form:fields.html.twig'


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            enumPersonDeviceHistoryAction: AppBundle\DBAL\EnumPersonDeviceHistoryActionType
        mapping_types:
                  enum: integer
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sensio_framework_extra:
    view:
        annotations: true
#
#fos_rest:
#    param_fetcher_listener: true
#    body_listener: true
#    format_listener:
#        enabled: true
#        rules:
#            - { path: '^/customer/api/', priorities: ['json', 'xml'], fallback_format: 'html' }
#    versioning: true
#    view:
#        view_response_listener: 'force'
#    zone:
#        - { path: ^/customer/api/* }
#    routing_loader:
#        default_format: json

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    assets:
        semantic_base_js:
            inputs:
                - 'bundles/app/semantic/dist/semantic.js'
        semantic_base_css:
            inputs:
                - "bundles/app/semantic/dist/semantic.rtl.css"
        font_droid_kufi_bold_eot:
            inputs:
                - "bundles/app/fonts/DroidKufi-Bold.eot"
            output: css/fonts/DroidKufi-Bold.eot
        font_droid_kufi_bold_ttf:
            inputs:
                - "bundles/app/fonts/DroidKufi-Bold.ttf"
            output: css/fonts/DroidKufi-Bold.ttf
        font_droid_kufi_bold_woff:
            inputs:
                - "bundles/app/fonts/DroidKufi-Bold.woff"
            output: css/fonts/DroidKufi-Bold.woff
        font_droid_kufi_bold_woff2:
            inputs:
                - "bundles/app/fonts/DroidKufi-Bold.woff"
            output: css/fonts/DroidKufi-Bold.woff2

        font_droid_kufi_regular_eot:
            inputs:
                - "bundles/app/fonts/DroidKufi-Regular.eot"
            output: css/fonts/DroidKufi-Regular.eot
        font_droid_kufi_regular_ttf:
            inputs:
                - "bundles/app/fonts/DroidKufi-Regular.ttf"
            output: css/fonts/DroidKufi-Regular.ttf
        font_droid_kufi_regular_woff:
            inputs:
                - "bundles/app/fonts/DroidKufi-Regular.woff"
            output: css/fonts/DroidKufi-Regular.woff
        font_droid_kufi_regular_woff2:
            inputs:
                - "bundles/app/fonts/DroidKufi-Regular.woff"
            output: css/fonts/DroidKufi-Regular.woff2

        font_droid_naskh_bold_eot:
            inputs:
                - "bundles/app/fonts/DroidNaskh-Bold.eot"
            output: css/fonts/DroidNaskh-Bold.eot
        font_droid_naskh_bold_ttf:
            inputs:
                - "bundles/app/fonts/DroidNaskh-Bold.ttf"
            output: css/fonts/DroidNaskh-Bold.ttf
        font_droid_naskh_bold_woff:
            inputs:
                - "bundles/app/fonts/DroidNaskh-Bold.woff"
            output: css/fonts/DroidNaskh-Bold.woff
        font_droid_naskh_bold_woff2:
            inputs:
                - "bundles/app/fonts/DroidNaskh-Bold.woff"
            output: css/fonts/DroidNaskh-Bold.woff2

        font_droid_naskh_regular_eot:
            inputs:
                - "bundles/app/fonts/DroidNaskh-Regular.eot"
            output: css/fonts/DroidNaskh-Regular.eot
        font_droid_naskh_regular_ttf:
            inputs:
                - "bundles/app/fonts/DroidNaskh-Regular.ttf"
            output: css/fonts/DroidNaskh-Regular.ttf
        font_droid_naskh_regular_woff:
            inputs:
                - "bundles/app/fonts/DroidNaskh-Regular.woff"
            output: css/fonts/DroidNaskh-Regular.woff
        font_droid_naskh_regular_woff2:
            inputs:
                - "bundles/app/fonts/DroidNaskh-Regular.woff"
            output: css/fonts/DroidNaskh-Regular.woff2
        font_semantic_eot:
            inputs:
                - "bundles/app/semantic/dist/themes/default/assets/fonts/icons.eot"
            output: css/themes/default/assets/fonts/icons.eot
        font_semantic_svg:
            inputs:
                - "bundles/app/semantic/dist/themes/default/assets/fonts/icons.svg"
            output: css/themes/default/assets/fonts/icons.svg
        font_semantic_ttf:
            inputs:
                - "bundles/app/semantic/dist/themes/default/assets/fonts/icons.ttf"
            output: css/themes/default/assets/fonts/icons.ttf
        font_semantic_woff:
            inputs:
                - "bundles/app/semantic/dist/themes/default/assets/fonts/icons.woff"
            output: css/themes/default/assets/fonts/icons.woff
        font_semantic_woff2:
            inputs:
                - "bundles/app/semantic/dist/themes/default/assets/fonts/icons.woff2"
            output: css/themes/default/assets/fonts/icons.woff2
        font_awesome_otf:
            inputs:
                - "assets/vendor/roapp-pixel-admin/help/assets/fontawesome/FontAwesome.otf"
            output: css/fontawesome/FontAwesome.otf
        font_awesome_eot:
            inputs:
                - "assets/vendor/roapp-pixel-admin/help/assets/fontawesome/fontawesome-webfont.eot"
            output: css/fontawesome/fontawesome-webfont.eot
        font_awesome_svg:
              inputs:
                  - "assets/vendor/roapp-pixel-admin/help/assets/fontawesome/fontawesome-webfont.svg"
              output: css/fontawesome/fontawesome-webfont.svg
        font_awesome_ttf:
              inputs:
                  - "assets/vendor/roapp-pixel-admin/help/assets/fontawesome/fontawesome-webfont.ttf"
              output: css/fontawesome/fontawesome-webfont.ttf
        font_awesome_woff:
              inputs:
                  - "assets/vendor/roapp-pixel-admin/help/assets/fontawesome/fontawesome-webfont.woff"
              output: css/fontawesome/fontawesome-webfont.woff



vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
        media_file:
            uri_prefix:         /uploads/media
            upload_destination: %kernel.root_dir%/../web/uploads/media

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig: ~

roapp_media:
    temporary_directory: "%kernel.root_dir%/../var/uploads"
    permanent_directory: "%kernel.root_dir%/../web/uploads/roapp_media"
    uploads:
        shipment_image:
            path: customer/dashboard
