app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app.customer.api.v1:
    resource: "@AppBundle/Controller/Customer/Api/V1/"
    prefix:   /customer/api/v1/

app.customer.dashboard:
    resource: "@AppBundle/Controller/Customer/Dashboard/"
    prefix:   /customer/dashboard/

app.driver.api.v1:
    resource: "@AppBundle/Controller/Driver/Api/V1/"
    prefix:   /driver/api/v1/

app.driver.dashboard:
    resource: "@AppBundle/Controller/Driver/Dashboard/"
    prefix:   /driver/dashboard/
