# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\Driver:
            algorithm: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        customer_provider:
            entity:
                class: AppBundle:Customer
        driver_provider:
            entity:
                class: AppBundle:Driver
                property: email
        in_memory:
            memory: ~

    firewalls:
        main:
            anonymous: ~
            logout: ~
            pattern: ^/customer/api
            guard:
                authenticators:
                    - app.customer_token_authenticator
        driver_dashboard:
            pattern: ^/driver/dashboard
            anonymous: ~
            form_login:
                login_path: /driver/dashboard/login
                check_path: /driver/dashboard/login
            logout:
                path: /driver/dashboard/logout
                target: /driver/dashboard
            provider: driver_provider

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        # require ROLE_ADMIN for /admin*
        # - { path: ^/, roles: ROLE_CUSTOMER }
