# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    sms_username: 9125995014
    sms_password: 7436
    sms_from: 50002016008194
#    parameter_name: value

services:
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@logger'

    app.sms:
        class: AppBundle\Utils\Sms
        arguments: ['%sms_username%', '%sms_password%', '%sms_from%']
    app.gcm:
        class: AppBundle\Utils\GCM
    app.form_error:
        class: AppBundle\Utils\FormError
    app.token_generator:
        class: AppBundle\Utils\TokenGenerator
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@service_container", "@security.authorization_checker", "@security.token_storage"]
        tags:
            - { name: knp_menu.menu_builder, method: createProfileSidebarMenu, alias: profile_side } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main_menu } # The alias is what is used to retrieve the menu
    app.shipment_assignment:
        class: AppBundle\Utils\AssignmentShipment
        arguments: ["@doctrine.orm.default_entity_manager"]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
