# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    sms_username: 9125995014
    sms_password: 7436
    sms_from: 50002016008194
    google_map_api: AIzaSyDITF2bWZw_taLim51isEQ43IRifnoVBZ4
#    parameter_name: value

services:
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@logger'

    app.sms:
        class: AppBundle\Utils\Sms
        arguments: ['%sms_username%', '%sms_password%', '%sms_from%']

    app.form_error:
        class: AppBundle\Utils\FormError

    app.token_generator:
        class: AppBundle\Utils\TokenGenerator

    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@service_container", "@security.authorization_checker", "@security.token_storage"]
        tags:
            - { name: knp_menu.menu_builder, method: createProfileSidebarMenu, alias: profile_side } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main_menu } # The alias is what is used to retrieve the menu

    app.cost_calculator:
        class: AppBundle\Utils\CostCalculator
        arguments: ['%time_based_mapping%', '%value_based_mapping%', '%google_map%']
    app.shipment_assignment:
        class: AppBundle\Utils\AssignmentShipment
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@app.notification_service"
            - "@translator"

    app.notification_service:
        class: AppBundle\Utils\NotificationService
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - '%google_firebase%'

    app.notification_message_factory:
        class: AppBundle\Utils\factories\NotificationMessageFactory
        arguments:
            - "@doctrine.orm.default_entity_manager"

    app.code_sender:
        class: AppBundle\Utils\CodeSender
        arguments:
            - "@app.notification_service"
            - "@app.sms"
            - "@translator"

    app.form_address:
        class: AppBundle\Form\Customer\Dashboard\AddressType
        arguments: ["@request_stack"]
        tags:
            - { name: form.type }
    app.form_role:
        class: AppBundle\Form\Operator\Dashboard\RoleType
        arguments: ["@doctrine"]
        tags:
            - { name: form.type }
    app.address_service:
        class: AppBundle\Utils\Services\AddressService
        arguments:
            - "@doctrine.orm.default_entity_manager"

    app.google_map_extension:
        class: AppBundle\Twig\GoogleMapExtension
        arguments: ['%google_map_api%']
        public: false
        tags:
            - { name: twig.extension }

    app.jdate_service:
            class: AppBundle\Utils\Services\JdateService

    app.shipment_listener:
            class: AppBundle\EventListener\ShipmentListener
            tags:
                - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }

    app.payment_service:
        class: AppBundle\Utils\Services\PaymentService
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@router"

    app.shipment_service:
        class: AppBundle\Utils\Services\ShipmentService
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@router"
            - "@security.token_storage"
            - "@app.shipment_assignment"

    app.shipment_discriminator_map_listener:
        class: AppBundle\EventListener\ShipmentDiscriminatorMapListener
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    app.business_unit_discriminator_map_listener:
        class: AppBundle\EventListener\BusinessUnitDiscriminatorMapListener
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    app.business_unit_service:
        class: AppBundle\Utils\Services\BusinessUnitService

    app.type.entity_hidden:
        class: AppBundle\Form\Customer\Dashboard\EntityHiddenType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
        - { name: form.type, alias: entity_hidden }
